# Generated by Django 5.1.3 on 2024-11-27 23:48

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=35)),
                ('model', models.CharField(max_length=35)),
                ('fuel', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('release_year', models.DateField()),
                ('state', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=25, null=True)),
                ('quilometers', models.IntegerField()),
                ('publishing_company', models.CharField(max_length=55)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.models.upload_image_car)),
            ],
        ),
    ]
